### ISSUE TITLE
X and Y go past limits

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/turbowarp.org#8] opened 2020-12-30 23:48 UTC
So I was doing a tutorial (by MathMathMath, scratch 2.0) and I took a look at the x and y. They went past the limits. The X was 581, meanwhile the Y was 435. Sometimes the Y goes to -435. This was only for the sprite nothing else. 

# _**To Reproduce**_

There is a series of the fixed scratch 2.0  MathMathMath projects.In part 5 of the fixed series, when you add the mouse script, move your mouse to the middle-top and there you have it, glitch reproduced. It happened in a another one, but not gonna talk about that 1,

# _**Os/Operating System**_

Chrome Book, Version 87.0.4280.109

**Comment by GarboMuffin** [comment] 2021-01-05 17:04
Duplicate of https://github.com/TurboWarp/scratch-gui/issues/37 I guess

**Closed as completed by GarboMuffin** 2021-01-05 17:04 UTC

**Comment by Dieforrobux** [comment] 2021-01-05 17:14
> Duplicate of [TurboWarp/scratch-gui#37](https://github.com/TurboWarp/scratch-gui/issues/37) I guess

yes basically but you weren't looking so i put it here

**Comment by Dieforrobux** [comment] 2021-01-05 17:14
* there
